version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
    environment:
      - FLASK_ENV=development
      - PORT=5000

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=https://58a5-2405-201-6807-88d6-50a4-9f46-355-87cd.ngrok-free.app
      - PORT=3000
      - NODE_ENV=development
      - BROWSER=none
    command: npm start 