[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  REACT_APP_BACKEND_URL = "https://zynga-backend-493402296384.us-central1.run.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 