[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  REACT_APP_BACKEND_URL = "https://codex-zynga-hackathon-1xkx.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 