[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  REACT_APP_BACKEND_URL = "https://58a5-2405-201-6807-88d6-50a4-9f46-355-87cd.ngrok-free.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 